### ISSUE TITLE
[FE] tui-editor 텍스트 바인딩

### ISSUE THREAD

**Issue by Pewww** [Tellin-App-Web/Tellin_Web_Frontend#14]
익스플로러 미 지원 현상으로 CkEditor5에서 tui editor로 변경했음.
지금 현재 에디터 변경은 완료된 상태인데 텍스트가 바인딩 되는지는 확인이 안 된 상태임.
일단 양방향 데이터 바인딩이 되는지 확인하고 안 되면 수정할 것

**Comment by yunedoopea2** [comment]
value 변수에 tui editor의 데이터 바인딩 설정
