### ISSUE TITLE
[FE] Ckedtior5 -> Tui Editor로 변경

### ISSUE THREAD

**Issue by Pewww** [Tellin-App-Web/Tellin_Web_Frontend#9]
기존 사용하려고 했던 Ckeditor5 버전이 IE 익스플로러를 전혀 지원을 안 한다는 문제점을 발견함.

이전 버전인 Ckeditor4를 사용하려고 했으나 디자인 시안과 맞는 balloon mode가 없기도 하고, 커스텀 빌드 등을 고려했을 때 Ckeditor는 프로젝트에 적합하지 않다는 결론을 내림.

따라서 원래 사용하기로 했던 Tui Editor를 쓰기로 정하였고, 이에 따라 디자인 시안이 살짝 바뀔 예정임.

**Comment by yunedoopea2** [comment]
vue-tui editor모듈 적용 -> 익스플로러 호환성 문제로 다시 Tui Editor로 모듈 적용 ->
디자인 시안 변경 필요함
